name: wasteless
description: WasteLess MVP.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  shared_preferences: ^2.0.18
  get_it: ^7.2.0
  dartz: ^0.10.1
  firebase_core: ^2.7.1
  google_maps_flutter: ^2.2.5
  flutter_bloc: ^8.1.2
  percent_indicator: ^4.2.3
  animated_text_kit: ^4.2.2
  firebase_database: ^10.1.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
    # fonts:
    - family: norwester
      fonts:
        - asset: fonts/norwester.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
