name: wasteless
description: WasteLess MVP.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  #shared_preferences: ^2.0.18
  get_it: ^7.2.0
  dartz: ^0.10.1
  firebase_core: ^2.7.1
  google_maps_flutter: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf
        # - asset: fonts/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
