// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7LE-tem-LIHxH0O1Y44cHvE42MEv-7Y',
    appId: '1:17109062365:web:ec331f25c9748b126a0134',
    messagingSenderId: '17109062365',
    projectId: 'wasteless-36ce0',
    authDomain: 'wasteless-36ce0.firebaseapp.com',
    storageBucket: 'wasteless-36ce0.appspot.com',
    measurementId: 'G-XC4P863ZQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jbcCRqLBnXObvckIAdgigIbNCOCv4ig',
    appId: '1:17109062365:android:5ef26a9834b496136a0134',
    messagingSenderId: '17109062365',
    projectId: 'wasteless-36ce0',
    storageBucket: 'wasteless-36ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gkAQ1JqBNBmAD9OqAXYfI1uzvxfQicI',
    appId: '1:17109062365:ios:5db9dc7c8eab73a16a0134',
    messagingSenderId: '17109062365',
    projectId: 'wasteless-36ce0',
    storageBucket: 'wasteless-36ce0.appspot.com',
    iosClientId: '17109062365-jie5qeenfbld2hafe3v0iu914veob8gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteless',
  );
}
